
version : '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    # restart: always
    container_name: dev_jenkins
    ports:
      - 8080:8080
      - 5000:5000
    container_name: jenkins
    # environment:
    #   - 
    volumes:
      - /home/pajkic/jenkins/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker